### ISSUE TITLE
non protonmail http connection attempts

### ISSUE THREAD

**Issue by ask2018** [vladimiry/protonmail-desktop-app#20] opened 2018-03-05 10:13 UTC
I have in my firewall enabled only https connection to mail.protonmail.com for this application. Everything works fine, but i've noticed in firewall log, that program constantly tries to connect also to these addresses. See blocked connections on this screenshot:
https://lut.im/Mu2eD4ZyNo/5rpxPJJHUpmTFgsJ.png
Why are there these connection attempts and how can I disable them in the settings?

**Comment by vladimiry** [comment] 2018-03-05 12:01
Going to investigate what are the blocked requests, app itself interacts with https://mail.protonmail.com only, you can see that looking into the code. Most likely blocked requests are update check requests happening on app start and then every 30 minutes.

**Comment by ask2018** [comment] 2018-03-05 12:39
Yes its on app start and then after some time period.
I've tried to look on DNS requests on program start and it wants to resolve those
github.com
mail.protonmail.com
ctldl.windowsupdate.com
ocsp.quovadisglobal.com
crl.quovadisglobal.com
ev.ocsp.quovadisglobal.com

So looks like mostly some certificate download requests, but why exactly?

**Comment by vladimiry** [comment] 2018-03-05 20:03
Can you try this version https://www.dropbox.com/s/fquubq186t9ldqn/protonmail-desktop-app-0.4.0-windows-nsis-installer.exe?dl=0? Having installed it, go to the "general" settings and disable `Check for updates and notify on app start` option there.

**Comment by ask2018** [comment] 2018-03-05 20:39
Github connection on port 443 is gone with version 0.4.0 and disabled check for updates, but the rest attempts to port 80 for these is still there and still not sure why exactly
ctldl.windowsupdate.com
ocsp.quovadisglobal.com
crl.quovadisglobal.com
ev.ocsp.quovadisglobal.com

**Comment by vladimiry** [comment] 2018-03-05 20:44
> still not sure why exactly

Have no idea so far about remaining requests, on Win 10 it's not reproducible (tried using Fiddler sniffer).

**Comment by vladimiry** [comment] 2018-03-05 21:04
Can you try to monitor the network activity using Fiddler or any other network sniffer having your firewall enabled and then disabled, to make sure that it's not a firewall somehow causes the issue. I'm not sure I will be able to play around this on Win 7 in the near future.

**Comment by ask2018** [comment] 2018-03-05 21:33
I did just quick check for DNS request using DNS Query Sniffer and its still there firewall enabled or disabled. But ocsp parts are also in browser and looks like its this https://support.quovadisglobal.com/kb/a415/what-is-ocsp-stapling.aspx
Also protonmail cert is verified by this company. So should be probably ok.

**Comment by vladimiry** [comment] 2018-03-05 21:35
Ok closing then. The good part is that we got a new feature "disabling update check" because of this issue :smile:

**Closed by vladimiry** 2018-03-05 21:35 UTC

**Comment by vladimiry** [comment] 2023-03-01 15:03
@fusionneur no idea. I'd recommend enabling [Block non "API entry point"-based network requests](https://github.com/vladimiry/ElectronMail/issues/312) to all email accounts.

**Comment by vladimiry** [comment] 2023-03-01 15:06
> on last update, i can see attempts to connect on port 80 as well

Try disabling the update check feature in the app's general settings block and restart the app then.

**Comment by vladimiry** [comment] 2023-03-01 18:14
> "block non api entry point... "

This only works for the webview the proton web clients loaded in, as enabled per account. But outer @electron itself might technically connect somewhere too. One option if such connection is downloading dictionaries for spellchecking feature, but this is a one time action per enabled language.

**Comment by vladimiry** [comment] 2023-05-24 12:48
@fusionneur https://github.com/electron/electron/issues/22995

**Comment by vladimiry** [comment] 2023-05-24 12:49
Consider disabling "update check" and "spellcheck" features in the app. Restart it and see if it helps.

**Comment by vladimiry** [comment] 2023-05-24 13:03
@fusionneur, those features, yes. I don't know what else to recommend, and would be interested to see if you are able to track down what triggers the unnecessary connection.

PS Maybe try running the app for a while without the proton accounts added (no need to remove the accounts, disabling by toggle should be enough, so webview doesn't get created/loaded), so we know if it linked to the proton's web clients.

**Comment by ask2018** [comment] 2023-05-24 13:32
I can confirm the connections attempts outside of Protonmail are there. I have enabled only Proton IPs and here is screenshot from my firewall log from last ~24 hours.

![firewall_log](https://github.com/vladimiry/ElectronMail/assets/35725232/7f6c9625-bc73-47d4-a0c9-f50c2ad5e640)

**Comment by vladimiry** [comment] 2023-05-24 16:45
Should be possible, but complicates the UX (explicit to user dictionaries downloading step vs in-background bootstrapping) and implementation/maintenance as each new app release will need to, depending on the feature state enabling, re-download all dictionaries in background from @electorn release page since it might include some updates (they serve it as a single archive, so all locales at once).
